### PR TITLE
Add chinese README.md

### PR DESCRIPTION
**Pull request by uiosun**
Hi, I translated the README.md.

Is `self.input` a keyword?

I try use `self.input`, but print get `nil`, so i update name is `self.input_v`.

### CODE REVIEW

**Comment by britzl** [comment]
Hi! Thank you for the translation!

self.input is not a keyword and it is a bit surprising that it was nil. Did it work when you changed it to self.input_v?

**Comment by uiosun** [comment]
Yep, I try again, the error show again, and `self.input_v` or other name is right working.

Maybe my windows system has some error, i submited a question of "[default android project can't print](https://forum.defold.com/t/default-mobile-project-cant-print-unsolved/54952)", can you remember?

Whatever, I want try again when my get back home, use Ubuntu system.

**Comment by uiosun** [comment]
I'm sorry, i should not use reload when updated code, this bring to error.

Now, everything is right!

**Comment by britzl** [comment]
Thank you!

**Pull request merged**
